console:
  signing_key: "xctWk*jW&E9VkudnmVSy+6T&(9RrpN!XxXPPUgrVJRbg!WUhpgVUyqTKvKYk(pX%"
  max_message_size_bytes: 409600
  username: "metabank_admin"
  password: "L&USpECT2wNerxWH&$$tzCgWxfCvMYXC"
logger:
  level: "DEBUG"
runtime:
  js_entrypoint: "build/index.js"
  token_expiry_sec: 1500
  http_key: "jBJwQTrnnDDT8YjAVsB8I3rqmXP0KOVFw1oqjxLfYLdOnj24cCddtUjrCZkBmp6XEd5YHHPFomFWvZbM3zCu9WdWhqgflPrRKYVclhnH9Yskvt619xsg51vI8XgVpwRiwpo9Z"
session:
  token_expiry_sec: 7200 # 2 hours
  refresh_encryption_key: "YHvam&xRwq%&A7(tKQqY9))yHZ4yN^I5P^3&&fzpLRmv@HqHkIUXIR^ksH4weWm3"
  encryption_key: "Rxy!2Sr*hJhatpST*^e)sgMWuBy3U@SwryRU2tv#!DP4%TbV$4h8R#G@(n5zadBL"
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
  server_key: "k!j2N*Gcvd#gAKy@mLCPpdutD#yMYIEW^(sKE$6wp7yE%C!eF@%fMbt8J6CESESg"
  
